name: e_shop
description: Flutter eCommerce App using Firebase Firestore

version: 1.0.0+1

environment:
  sdk: ">=2.9.0-8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.2.0


  grouped_buttons: ^1.0.4
  google_sign_in: ^5.0.1
  flutter_facebook_login: ^3.0.0
  js: ^0.6.2
  im_stepper: ^0.1.3
  cupertino_icons: ^0.1.2
  cloud_firestore: ^2.2.0
  cloud_firestore_web: ^2.1.0
  firebase_auth: ^1.2.0
  shared_preferences: ^0.5.6+1
  fluttertoast: ^8.0.7
  image_picker: ^0.6.3+1
  firebase_storage: ^8.1.0
  flutter_staggered_grid_view: ^0.3.0
  provider: ^4.0.4
  path_provider: ^0.5.0+1
  flutter_slidable: ^0.6.0
  image: ^2.0.7
  page_transition: ^2.0.2
  full_screen_image: ^1.0.2
  firebase_messaging: ^10.0.0
  firebase_analytics: ^8.0.0
  flutter_rating_bar: ^4.0.0



  intl:


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
        - asset: assets/fonts/SourceSansPro-Regular.ttf

  assets:
    - images/google.png
    - images/facebook.png
    - images/welcome.png
    - images/login.png
    - images/admin.png
    - images/cash.png
    - images/tshirt.png
    - images/Jacket.png
    - images/jeans.png
    - images/trousers2.png
    - images/hooded-jacket.png
    - images/sneakers.png
    - images/shorts.png
    - images/bags.png
    - images/emptyCart.png
    - images/address.png
    - images/MEN.jpg
    - images/WOMAN.jpg
    - images/KIDS.jpg
    - images/USED.jpg
    - images/truck.png
    - images/shirt.png



