name: e_shop
description: Flutter eCommerce App using Firebase Firestore from Coding Cafe

version: 1.0.0+1

environment:
  sdk: ">=2.9.0-8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+9

  grouped_buttons: ^1.0.4
  google_sign_in: ^5.0.1
  flutter_facebook_login: ^3.0.0
  js: ^0.6.2
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.12.9+5
  firebase_messaging: ^5.1.4
  firebase_auth: ^0.14.0+5
  shared_preferences: ^0.5.6+1
  fluttertoast: ^3.1.3
  image_picker: ^0.6.3+1
  firebase_storage: ^3.1.1
  flutter_staggered_grid_view: ^0.3.0
  provider: ^4.0.4
  path_provider: ^0.5.0+1
  flutter_slidable: ^0.6.0
  image: ^2.0.7
  intl:


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
        - asset: assets/fonts/SourceSansPro-Regular.ttf

  assets:
    - images/google.png
    - images/facebook.png
    - images/welcome.png
    - images/login.png
    - images/admin.png
    - images/cash.png
    - images/tshirt.png
    - images/Jacket.png
    - images/jeans.png
    - images/trousers2.png
    - images/hooded-jacket.png
    - images/sneakers.png
    - images/shorts.png
    - images/bags.png
    - images/emptyCart.png



